version: 3
type: "conversation"
name: "Change kubernetes deployment replicas"
steps:
  - type: "action"
    id: "k8s_namespaces"
    action:
      name: "list_namespace"
      store: "kubernetes"
      runner: ${default.runner}
      parameters: {}
  - type: "input"
    value_type: "enum"
    id: "selected_namespace"
    prompt: "Select the namespace of the deployment you want to change"
    possible_values: "${k8s_namespaces}"
  - type: "action"
    id: "k8s_deployments"
    action:
      name: "list_deployment"
      store: "kubernetes"
      runner: ${default.runner}
      parameters:
        deployment_name: ""
        namespace: "${selected_namespace}"
  - type: "input"
    value_type: "enum"
    id: "selected_deployment"
    prompt: "Select the deployment you want to change"
    possible_values: "${k8s_deployments}"
  - type: "action"
    id: "current_replicas"
    label: ""
    action:
      name: "get_deployment_replicas"
      store: "kubernetes"
      runner: ${default.runner}
      parameters:
        deployment_name: "${selected_deployment}"
        namespace: "${selected_namespace}"
  - type: "message"
    id: "print_current_replicas"
    prompt: "📝 Current replicas for deployment *${selected_deployment}* in namespace *${selected_namespace}*:\n ```${current_replicas}```"
  - type: "input"
    value_type: "text"
    id: "new_amount_of_replicas"
    prompt: "Enter a new value for the replicas amount:"
  - type: "input"
    value_type: "boolean"
    id: "validate"
    prompt: "⚠️ Changing replicas amount for deployment ${selected_deployment} in namespace ${selected_namespace} from ${current_replicas} to ${new_amount_of_replicas}. Continue?"
  - type: "condition"
    id: "condition"
    if:
      arg: "${validate}"
      is: "equals"
      arg2: "true"
      then:
        - type: "message"
          id: "notify"
          prompt: "🔄 Updating replicas for deployment ${selected_deployment} in namespace ${selected_namespace}.."
        - type: "action"
          id: "set_new_replicas_count"
          label: ""
          action:
            name: "set_deployment_replicas"
            store: "kubernetes"
            runner: ${default.runner}
            parameters:
              deployment_name: "${selected_deployment}"
              namespace: "${selected_namespace}"
              replicas: "${new_amount_of_replicas}"
        - type: "message"
          id: "print"
          prompt: "✅ *Done!*"
      else:
        - type: "message"
          id: "cancel"
          prompt: "❌ *Cancelled!*\n"
